theme = "catppuccin_macchiato"

[editor]
color-modes = true
cursorline = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.insert]
j = { j = "normal_mode" }

[keys.normal]
"C-l" = "jump_view_right"
"C-h" = "jump_view_left"

[keys.normal.space]
w = ":write"
q = ":quit"
