theme = "catppuccin_macchiato"

[editor]
color-modes = true
cursorline = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
j = { j = "normal_mode" }

[keys.normal]
"C-l" = "jump_view_right"
"C-h" = "jump_view_left"

[keys.normal.space]
w = ":write"
q = ":quit"
