version: 1.0.0
formatVersion: 1
general:
  language: ja
  colorScheme: dark
  themeColor: Sunset
keyboardShortcuts:
  global:
    completeTask: ''
    addTopTask: ''
    showTagManagement: ''
    addBottomTask: ''
    showTaskList: cmd+.
  taskListOverlay:
    addBottom: a
    moveDown: j
    delete: d
    edit: e
    complete: c
    moveToTop: return
    moveUp: k
    close: escape
    addTop: o
  tagSelection:
    moveDown: ctrl+j
    moveUp: ctrl+k
    toggle: ctrl+i
  tagManagementOverlay:
    moveUp: k
    cycleColor: tab
    rename: r
    delete: d
    close: escape
    moveDown: j
    add: a
    toggleActive: return
