vim.opt.autoindent = true
vim.opt.smartindent = true
vim.opt.expandtab = true
vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.cursorline = true
vim.opt.showtabline = 2
vim.opt.showmatch = true
vim.opt.number = true
vim.opt.title = true
vim.opt.backspace = "indent,eol,start"
vim.opt.inccommand = "split"
vim.opt.hidden = true
vim.opt.termguicolors = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.conceallevel = 0
vim.opt.encoding="utf-8"
vim.opt.fileencoding="utf-8"
vim.opt.fileencodings="utf-8,iso-2022-jp,euc-jp,ucs-2,cp932,sjis"
vim.opt.clipboard="unnamedplus"
vim.opt.swapfile=false
vim.opt.pumblend=10
vim.opt.winblend=10
vim.opt.foldmethod="syntax"
vim.opt.foldenable=false
vim.opt.signcolumn="yes:2"
vim.opt.cmdheight=0
vim.opt.undodir=vim.fn.expand("~/.config/nvim.undo")
vim.opt.undofile=true
vim.opt.listchars="tab:>-"
vim.opt.list=true
vim.opt.mouse = nil
