format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$package\
$custom\
$kubernetes\
$fill\
$cmd_duration\
$jobs\
$battery\
$time\
$status\
$line_break\
$character"""


[directory]
home_symbol = "${HOME}"
truncation_length = 0
format = '[$path]($style)[$read_only]($read_only_style) '
style = 'underline cyan'

[git_branch]
truncation_symbol = ''
format = '| [$branch(:$remote_branch)]($style)'
style = 'underline purple'

[git_status]
conflicted = "${count}="
ahead = "${count}↑"
behind = "${count}↓"
diverged = "${count}⇕"
untracked = "${count}?"
stashed = "${count}*"
modified = "${count}!"
staged = '[++\($count\)](green)'
renamed = "${count}»"
deleted = "${count}✘"
format = ' | ([\[$all_status$ahead_behind\]]($style)) '
style = 'underline red'

[custom.gitmail]
command = "git config user.email"
when = "[ -d .git ] && echo .git || git rev-parse --git-dir > /dev/null 2>&1"
format = "| [$output](underline fg:blue) "

[kubernetes]
format = '| [$context](underline fg:green)'
disabled = false

[fill]
symbol = ' '

[package]
format = '| [$version]($style) '
version_format = '${raw}'
style='underline 208'

[time]
disabled = false
format = '[  $time ]($style)'
time_format= '%F(%a) %H:%M:%S%.3f'
style='underline blue'

[character]
success_symbol = "[>](bold green)"
