[git_status]
conflicted = "${count}="
ahead = "${count}↑"
behind = "${count}↓"
diverged = "${count}⇕"
untracked = "${count}?"
stashed = "${count}*"
modified = "${count}!"
staged = '[++\($count\)](green)'
renamed = "${count}»"
deleted = "${count}✘"

[directory]
home_symbol = "${HOME}"
truncation_length = 0

[custom.gitmail]
command = "git config user.email"
when = "[ -d .git ] && echo .git || git rev-parse --git-dir > /dev/null 2>&1"
format = " | [$output](underline fg:blue) | "
