[git_status]
conflicted = "${count}="
ahead = "${count}↑"
behind = "${count}↓"
diverged = "${count}⇕"
untracked = "${count}?"
stashed = "${count}*"
modified = "${count}!"
staged = '[++\($count\)](green)'
renamed = "${count}»"
deleted = "${count}✘"

[directory]
home_symbol = "${HOME}"
